import Head from "next/head";
import * as S from "./styles";
import { Inter, Saira } from "next/font/google";
import ProductCard from "@/components/productCard";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container className={`${inter.variable} ${saira.variable}`}>
        <h1>Todos os produtos</h1>
        <section>
          <ProductCard />
        </section>
      </S.Container>
    </>
  );
}
